[build]
  # No build process needed for static site
  command = ""
  publish = "."

[build.environment]
  # Environment variables (if needed in future)

[[headers]]
  # Apply headers to all files
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache control for assets
    Cache-Control = "public, max-age=31536000"

[[headers]]
  # Special headers for HTML files
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  # Headers for JavaScript files
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Headers for texture files
  for = "/assets/textures/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect rules (if needed)
[[redirects]]
  from = "/solar-system"
  to = "/"
  status = 301

[[redirects]]
  from = "/planets"
  to = "/"
  status = 301

# Error pages
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200